theme = "xmin"
baseURL = "https://danieldulaney.com"
languageCode = "en-us"
title = "Daniel Dulaney"

[taxonomies]
tag = "tags"
series = "series"

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Series"
url = "/series"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 3